name: polkawallet_sdk
description: Flutter SDK for building plugin package for polkawallet.
version: 0.6.2
homepage: https://polkawallet.io
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  webview_flutter: ^4.7.0
  flutter_inappwebview: ^6.1.4
  shared_preferences: ^2.2.3
  get_storage: ^2.1.1
  json_annotation: ^4.8.1
  flutter_aes_ecb_pkcs5: #^0.1.3
    # path: ../flutter_aes_ecb_pkcs5
    git:
      url: https://github.com/poka-IT/flutter_aes_ecb_pkcs5.git
      ref: 5a98954213693863fa9d9c2692f3cf9e2ca23712
  flutter_secure_storage: ^9.2.2
  convert: ^3.1.1
  mobx: ^2.3.3+2
  bip39: ^1.0.6
  web3dart: ^2.6.1
  url_launcher: ^6.2.6

dev_dependencies:
  mobx_codegen: ^2.6.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - js_as_extension/dist/main.js

  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
